import { GoogleGenAI } from "@google/genai";



const ai = new GoogleGenAI({ apiKey: process.env.Google_API_KEY });
/**
 * Function to generate the response from the Google GenAI model.
 * @param {*} phrase  the input phrase to be processed by the AI model
 * @returns  The response text generated by the AI model to be used for further processing.
 */
export async function main(phrase) {
    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.0-flash",
            contents: phrase,
        });
 
        return response.text;
    } catch (error) {
        console.error("model is busy, try again later");
    }
}
